name = "cloud-notepad"
main = "src/index.js"
compatibility_date = "2022-05-13"

kv_namespaces = [
  { binding = "NOTES", id = "65c09d325f704fbda39012e69760814f" },
  { binding = "SHARE", id = "8925e807a2e449c0a9cf188d7bcbf846" }
]